alias: "Zendure Tempo - Bleu - Normal"
description: "Jour Bleu : mode smart normal"
trigger:
  - platform: state
    entity_id: sensor.rte_tempo_couleur_actuelle
    to: "Bleu"
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.zendure_tempo_enabled
    state: "on"
  - condition: state
    entity_id: sensor.rte_tempo_couleur_actuelle
    state: "Bleu"
  - condition: not
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: sensor.rte_tempo_prochaine_couleur
            state: "Rouge"
          - condition: state
            entity_id: binary_sensor.rte_tempo_heures_creuses
            state: "on"
action:
  - service: number.set_value
    target:
      entity_id: number.hyper_2000_input_limit
    data:
      value: "{{ states('input_number.zendure_tempo_input_limit_max') | int }}"
  - service: number.set_value
    target:
      entity_id: number.hyper_2000_output_limit
    data:
      value: "{{ states('input_number.zendure_tempo_output_limit_max') | int }}"
  - service: number.set_value
    target:
      entity_id: number.hyper_2000_soc_set
    data:
      value: "{{ states('input_number.zendure_tempo_soc_normal') | int }}"
  - service: logbook.log
    data:
      name: "Zendure Tempo"
      message: "Bleu - Mode normal"
mode: single
